### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by Britnell** [igorm84/spotify-astro-transitions#5]
i'm curious if anyone else gets there weird visual glitches,
- overlapping ghost headers from other cards
- when mousing mouse over / off a card some ghost glitches of other cards' images (see far right card)
![image](https://github.com/igorm84/spotify-astro-transitions/assets/19732260/44a08f3b-5120-494f-8293-d51531522ae9)

is that a bug in my browser? (maybe as transitions are still fresh? )

**Comment by igorm84** [comment]
@Britnell transitions are very experimental feature, also astro is working hard to improve it and enable us to have more control. 

What browser and can you detail more about your device?

Can you send a video showing up these problems you having?

Did you compared it t some others view transitions demos?

**Comment by Britnell** [comment]
hey, sorry these are just from my OS it seems, i've seen similar glitches on other website , apologies
( funnily enough i also get glitches on the real spotify )
